config/routes.rb
Rails.application.routes.draw do
  root 'items#index'

  get    '/auth/:provider'          => 'omniauth#auth',    as: :auth
  get    '/auth/:provider/callback' => 'session#create'
  get    '/auth/failure'            => 'session#failure'

  get  '/login'  => 'session#new'
  post '/login'  => 'session#create'
  get  '/logout' => 'session#destroy'

  resources :items
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Factory method to create a user from some omniauth data
  # Omniauth will use this to build a *NEW* user for us
  def self.from_omniauth(authentication_data)
    user = User.where(provider: authentication_data['provider'],
                      uid: authentication_data['uid']).first_or_create

    Rails.logger.debug "The user is #{user.inspect}"

    user.name         = authentication_data.info.name
    user.nickname     = authentication_data.info.nickname
    user.access_token = authentication_data.info.access_token

    user.save!

    Rails.logger.debug "After saving, the user is #{user.inspect}"

    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # Assign the current user
  def current_user=(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  helper_method :current_user

  # Returns a boolean representing if the user is logged in
  def logged_in?
    !!current_user
  end
  helper_method :logged_in?

  # Method to use in filter to ensure the user is logged in
  def authenticate!
    unless logged_in?
      redirect_to auth_path(provider: 'github')
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate!, except: [:index]

  # GET /items
  def index
    @items = Item.all
  end

  # GET /items/1
  def show
    @item = Item.find(params[:id])
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to @item, notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /items/1
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to @item, notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /items/1
  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_url, notice: 'Item was successfully destroyed.'
  end

  private

  # Only allow a trusted parameter "white list" through.
  def item_params
    params.require(:item).permit(:name, :description, :price, :purchased_on)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  # logging in
  def new
  end

  # handle the post from the login page
  def create
    self.current_user = User.from_omniauth(request.env['omniauth.auth'])

    if current_user
      redirect_to root_path
    else
      redirect_to auth_path(provider: 'github')
    end
  end

  # logout
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  # Show the failure page
  def failure
    # TODO, create failure.html.erb
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/items/_form.html.slim
= form_for(@item, html: { class: "form-horizontal", role: "form" }) do |f|
  - if @item.errors.any?
    .alert.alert-danger.alert-dismissable role="alert"
      button.close type="button" data-dismiss="alert"
        span aria-hidden="true"
          | &times;
        span.sr-only
          | Close
      h4= "#{pluralize(@item.errors.count,"error")} prohibited this item from being saved:"
      ul
        - @item.errors.full_messages.each do |msg|
          li= msg
  .form-group
    = f.label :name, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :name, class: "form-control"
  .form-group
    = f.label :description, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :description, class: "form-control"
  .form-group
    = f.label :price, class: "col-sm-2 control-label"
    .col-sm-10
      = f.number_field :price, class: "form-control"
  .form-group
    = f.label :purchased_on, class: "col-sm-2 control-label"
    .col-sm-10
      = f.date_select :purchased_on, class: "form-control"
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: "btn btn-primary"

app/views/items/edit.html.slim
.page-header
  = link_to items_path, class: 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    | Back
  = link_to @item, class: 'btn btn-primary' do
    span.glyphicon.glyphicon-info-sign
    | Show
  h1 Editing item

= render 'form'

app/views/items/index.html.slim
.page-header
  = link_to new_item_path, class: 'btn btn-primary' do
    span.glyphicon.glyphicon-plus
    | New Item
  h1 Listing items

.table-responsive
  table.table.table-striped.table-bordered.table-hover
    thead
      tr
        th Name
        th Description
        th Price
        th Purchased on
        th colspan=3
    tbody.table-body
      - @items.each do | item |
        tr
          td= item.name
          td= item.description
          td= item.price
          td= item.purchased_on
          td= link_to item do
            span.glyphicon.glyphicon-ok
          td= link_to edit_item_path(item)
            span.glyphicon.glyphicon-pencil
          td= link_to item, method: :delete, data: { confirm: 'Are you sure?' }
            span.glyphicon.glyphicon-remove

app/views/items/new.html.slim
.page-header
  = link_to items_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    | Back
  h1 New item

= render 'form'

app/views/items/show.html.slim
.page-header
  = link_to items_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to edit_item_path(@item), class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-pencil
    |  Edit 
  h1 Show item
dl.dl-horizontal
  dt Name:
  dd = @item.name
  dt Description:
  dd = @item.description
  dt Price:
  dd = @item.price
  dt Purchased on:
  dd = @item.purchased_on

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"
    meta name="description" content=""
    meta name="author" content=""
    title
      | YardsaleGithub
    /! HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    nav.navbar.navbar-inverse.navbar-fixed-top role="navigation"
      .container
        .navbar-header
          button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"
            span.sr-only
              | Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to "#", class: "navbar-brand" do
            | YardsaleGithub
        #navbar.collapse.navbar-collapse
          ul.nav.navbar-nav
            li.active
              = link_to "Home", "#"
          ul.nav.navbar-nav.navbar-right
            - if logged_in?
              li.navbar-text= current_user.name
              li= link_to 'Logout', logout_path
            - else
              li
                = link_to auth_path(provider: 'github'), class: "btn btn-block btn-social btn-github" do
                  span.fa.fa-github
                  | login 

    .container
      - flash.each do |name, msg|
        = content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do
          button.close type="button" data-dismiss="alert"
            span aria-hidden="true"
              | &times;
            span.sr-only
              | Close
          = msg
      = yield

app/views/session/new.html.slim
/ <a class="btn btn-block btn-social btn-twitter">
/   <span class="fa fa-twitter"></span> Sign in with Twitter
/ </a>
.row
  .col-md-3
    = link_to auth_path(provider: 'github'), class: "btn btn-block btn-social btn-github" do
      span.fa.fa-github
      | Login with Github